SELECT FIRST_NAME, LAST_NAME, EMAIL, COMPANY
FROM EX1_024030.CUSTOMERS
WHERE COMPANY LIKE 'C%';

SELECT COUNT(PRODUCT_ID) CUENTA
FROM EX1_024030.PRODUCTS
WHERE LIST_PRICE > 100;

SELECT *
FROM EX1_024030.ORDERS ORD
    INNER JOIN EX1_024030.ORDERS_PRODUCTS OP
        ON ORD.ORDER_ID = OP.ORDER_ID
WHERE OP.QUANTITY = 1;

SELECT *
FROM EX1_024030.PRODUCTS PROD
    INNER JOIN EX1_024030.CULTURES CUL
        ON PROD.CULTURE_ID = CUL.CULTURE_ID
WHERE CUL.CULTURE LIKE 'M%';